-- This file imports all sub-files in the library. It is created automatically during compilation. Do not edit this manually.
import Corelib.Algebra.Group.Operations
import Corelib.Algebra.Group.ZeroOne
import Corelib.Data.Array.Defs
import Corelib.Data.Int.Notation
import Corelib.Data.Nat.Basic
import Corelib.Data.Nat.Defs
import Corelib.Data.Nat.Notation
import Corelib.Data.Ordering.Basic
import Corelib.Data.Rat.Init
import Corelib.Data.Set.Defs
import Corelib.Data.String.Defs
import Corelib.Data.Subtype
import Corelib.Lean.Elab.Tactic.Basic
import Corelib.Lean.Elab.Term
import Corelib.Lean.EnvExtension
import Corelib.Lean.Expr.Basic
import Corelib.Lean.Expr.Rat
import Corelib.Lean.Expr.ReplaceRec
import Corelib.Lean.Meta
import Corelib.Lean.Meta.CongrTheorems
import Corelib.Lean.Meta.Simp
import Corelib.Lean.Name
import Corelib.Logic.Basic
import Corelib.Logic.ExistsUnique
import Corelib.Logic.Function.Basic
import Corelib.Logic.Function.Defs
import Corelib.Logic.IsEmpty
import Corelib.Logic.Lemmas
import Corelib.Logic.Nonempty
import Corelib.Logic.Nontrivial.Defs
import Corelib.Logic.Relator
import Corelib.Order.Basic
import Corelib.Order.Defs.LinearOrder
import Corelib.Order.Defs.PartialOrder
import Corelib.Order.Defs.Unbundled
import Corelib.Order.Notation
import Corelib.Tactic.Basic
import Corelib.Tactic.Cases
import Corelib.Tactic.CasesM
import Corelib.Tactic.Coe
import Corelib.Tactic.CongrExclamation
import Corelib.Tactic.Contrapose
import Corelib.Tactic.Conv
import Corelib.Tactic.Convert
import Corelib.Tactic.Core
import Corelib.Tactic.Eqns
import Corelib.Tactic.ExtendDoc
import Corelib.Tactic.GCongr.Core
import Corelib.Tactic.GCongr.CoreAttrs
import Corelib.Tactic.GCongr.ForwardAttr
import Corelib.Tactic.Inhabit
import Corelib.Tactic.Lemma
import Corelib.Tactic.Lift
import Corelib.Tactic.OfNat
import Corelib.Tactic.PushNeg
import Corelib.Tactic.Simps.Basic
import Corelib.Tactic.Simps.NotationClass
import Corelib.Tactic.SplitIfs
import Corelib.Tactic.Spread
import Corelib.Tactic.Tauto
import Corelib.Tactic.ToAdditive
import Corelib.Tactic.ToAdditive.Frontend
import Corelib.Tactic.TypeStar
import Corelib.Util.GetAllModules
import Corelib.Util.MemoFix
