[project]
name = "byb-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ray[data]==2.49.0",
    "vllm==0.10.1.1",
]
